name: rtc-discovery
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - biopython
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - requests
  - tqdm
  - jupyter
  - ipykernel
  - pip
