"""
Script 08_2: Docking Preparation — NSP10-NSP14
===============================================
Project : panCov-rtc-discovery
Author  : Olivier Nsekuye
Date    : 2025

What this script does:
  Prepares the receptor file for virtual screening.
  Uses 7DIY as primary receptor (highest resolution crystal).
  Extracts receptor (NSP10+NSP14) and removes waters/ligands.
  Outputs docking box configuration for VirtualFlow/AutoDock Vina.
  Saves all configs to 03-virtual-screening/NSP10-NSP14_2/

How to run:
  conda activate rtc-discovery
  cd ~/projects/rtc-pan-coronavirus
  python scripts/08_docking_prep_NSP10-NSP14_2.py
"""

import json
from pathlib import Path
from Bio import PDB
from Bio.PDB import PDBIO, Select

PROJECT  = Path.home() / "projects" / "rtc-pan-coronavirus"
PDB_DIR  = PROJECT / "00-reference" / "pdb_structures"
RES_DIR  = PROJECT / "02-validation" / "NSP10-NSP14"
DOCK_DIR = PROJECT / "03-virtual-screening" / "NSP10-NSP14_2"
DOCK_DIR.mkdir(parents=True, exist_ok=True)

# ── Docking box from Script 07_2 (7DIY Pocket 3) ──────────
DOCKING_BOX = {
    "center_x": -4.776,
    "center_y":  7.298,
    "center_z": -25.886,
    "size_x":   31.685,
    "size_y":   34.288,
    "size_z":   48.982,
}

# ── Conserved hotspot residues ─────────────────────────────
HOTSPOTS_NSP10 = [5, 19, 21, 40, 42, 44, 45, 80, 93]
HOTSPOTS_NSP14 = [4, 7, 8, 9, 10, 20, 25, 27, 127, 201]


class ProteinOnlySelect(Select):
    """Keep only ATOM records from chains A and B — no HETATM, no water"""
    def accept_residue(self, residue):
        return residue.id[0] == " "   # only standard residues

    def accept_chain(self, chain):
        return chain.id in ("A", "B")


def prepare_receptor(pdb_in, pdb_out):
    """Strip waters and heteroatoms, keep chains A+B only"""
    parser    = PDB.PDBParser(QUIET=True)
    structure = parser.get_structure("receptor", pdb_in)
    io        = PDBIO()
    io.set_structure(structure)
    io.save(str(pdb_out), ProteinOnlySelect())

    # Count residues saved
    structure2 = parser.get_structure("check", pdb_out)
    n = sum(1 for _ in structure2.get_residues())
    print(f"  OK    Receptor: {n} residues saved → {pdb_out.name}")
    return n


def write_vina_config(box, receptor_path, out_path):
    """Write AutoDock Vina configuration file"""
    config = f"""# AutoDock Vina configuration
# NSP10-NSP14 interface — SARS-CoV-2 (7DIY)
# Primary hotspot: HIS80(NSP10) - ASP126(NSP14) salt bridge
# Generated by Script 08_2

receptor = {receptor_path.name}

center_x = {box['center_x']}
center_y = {box['center_y']}
center_z = {box['center_z']}

size_x = {box['size_x']}
size_y = {box['size_y']}
size_z = {box['size_z']}

exhaustiveness = 16
num_modes      = 9
energy_range   = 3
"""
    out_path.write_text(config)
    print(f"  OK    Vina config → {out_path.name}")


def write_virtualflow_config(box, receptor_path, out_path):
    """Write VirtualFlow docking box config"""
    config = {
        "target":     "NSP10-NSP14",
        "receptor":   str(receptor_path),
        "pdb_source": "7DIY",
        "resolution": "2.69A",
        "hotspot":    "HIS80(NSP10)-ASP126(NSP14)",
        "box":        box,
        "hotspots": {
            "NSP10_conserved": HOTSPOTS_NSP10,
            "NSP14_conserved": HOTSPOTS_NSP14,
        },
        "notes": (
            "PPI interface docking box. Low fpocket druggability "
            "expected for PPI — use hotspot-guided box. HIS80 "
            "fully conserved across 5 coronaviruses (score=1.0)."
        ),
    }
    with open(out_path, "w") as f:
        json.dump(config, f, indent=2)
    print(f"  OK    VirtualFlow config → {out_path.name}")


def print_summary(box):
    print(f"\n  Docking box summary:")
    print(f"  {'Center X':<12}: {box['center_x']:>10.3f} Å")
    print(f"  {'Center Y':<12}: {box['center_y']:>10.3f} Å")
    print(f"  {'Center Z':<12}: {box['center_z']:>10.3f} Å")
    print(f"  {'Size X':<12}: {box['size_x']:>10.3f} Å")
    print(f"  {'Size Y':<12}: {box['size_y']:>10.3f} Å")
    print(f"  {'Size Z':<12}: {box['size_z']:>10.3f} Å")
    vol = box['size_x'] * box['size_y'] * box['size_z']
    print(f"  {'Volume':<12}: {vol:>10.1f} Å³")


def main():
    print("\n" + "="*55)
    print("  Script 08_2: Docking Prep — NSP10-NSP14")
    print("  Receptor: 7DIY (SARS-CoV-2, 2.69Å)")
    print("="*55 + "\n")

    pdb_in   = PDB_DIR / "7DIY.pdb"
    receptor = DOCK_DIR / "receptor_NSP10-NSP14_2.pdb"
    vina_cfg = DOCK_DIR / "vina_config_NSP10-NSP14_2.txt"
    vf_cfg   = DOCK_DIR / "virtualflow_config_NSP10-NSP14_2.json"

    # ── Step 1: Prepare receptor ──────────────────────────
    print("  Step 1: Preparing receptor\n")
    prepare_receptor(pdb_in, receptor)

    # ── Step 2: Write docking configs ─────────────────────
    print("\n  Step 2: Writing docking configurations\n")
    write_vina_config(DOCKING_BOX, receptor, vina_cfg)
    write_virtualflow_config(DOCKING_BOX, receptor, vf_cfg)

    # ── Step 3: Print summary ─────────────────────────────
    print("\n  Step 3: Docking box")
    print_summary(DOCKING_BOX)

    # ── Step 4: Verify hotspot residues in receptor ───────
    print(f"\n  Step 4: Verifying hotspot residues in receptor")
    parser    = PDB.PDBParser(QUIET=True)
    structure = parser.get_structure("r", receptor)
    found_a, found_b = [], []
    for model in structure:
        for chain in model:
            for res in chain:
                if chain.id == "A" and res.id[1] in HOTSPOTS_NSP10:
                    found_a.append(res.id[1])
                if chain.id == "B" and res.id[1] in HOTSPOTS_NSP14:
                    found_b.append(res.id[1])

    print(f"  NSP10 hotspots in receptor ({len(found_a)}"
          f"/{len(HOTSPOTS_NSP10)}): {sorted(found_a)}")
    print(f"  NSP14 hotspots in receptor ({len(found_b)}"
          f"/{len(HOTSPOTS_NSP14)}): {sorted(found_b)}")

    missing_a = set(HOTSPOTS_NSP10) - set(found_a)
    missing_b = set(HOTSPOTS_NSP14) - set(found_b)
    if missing_a:
        print(f"  ⚠️  Missing NSP10: {sorted(missing_a)}")
    if missing_b:
        print(f"  ⚠️  Missing NSP14: {sorted(missing_b)}")
    if not missing_a and not missing_b:
        print(f"  ✅ All hotspot residues present in receptor")

    print(f"\n  Output files:")
    print(f"  03-virtual-screening/NSP10-NSP14_2/")
    print(f"  ├── receptor_NSP10-NSP14_2.pdb")
    print(f"  ├── vina_config_NSP10-NSP14_2.txt")
    print(f"  └── virtualflow_config_NSP10-NSP14_2.json")
    print("="*55 + "\n")


if __name__ == "__main__":
    main()
